### ISSUE TITLE
Move to gulpjs org?

### ISSUE THREAD

**Issue by phated** [gulpjs/ordered-read-streams#20]
Hey @armed - I was wondering if you'd like the @gulpjs org to take over this project.  We rely on it for glob-stream and the couple of outstanding issues might benefit from the visibility of the gulp org.

**Comment by armed** [comment]
Hey, @phated sorry for late reply. Agree, this rep should be moved. Should I transfer it to @gulpjs organization or to you?

**Comment by phated** [comment]
Feel free to transfer it to me and then I'll move it over there. Thanks!

**Comment by armed** [comment]
Hey, @phated you should remove fork before I transfer.

**Comment by phated** [comment]
Done! (I actually renamed and archived my fork but that should work)

**Comment by armed** [comment]
That's strange. Still can't transfer `phated already has a repository in the armed/ordered-read-streams network`.

**Comment by phated** [comment]
@armed that's super weird!  I've reviewed any differences and found it was fine to delete the repo.  Sorry for the inconvenience!

**Comment by armed** [comment]
Ok, done. Transfer request sent. I'll miss you. `ordered-read-streams` :cry:
